baseURL = 'http://www.rajwadkar.us/protean.github.io/'
languageCode = 'en-us'
title = 'ABC Widgets, Inc.'
theme = "nightfall"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
user = "print-USERNAME"
hostname = "print-HOSTNAME"
  [params.author]
    name = "MAIN PAGE "  # Website and RSS feed author

readingTime = false  # Show reading time on post page
published = false  # Show published data on post page

[[params.social]]
key = 0
name = "instagram"
url = "https://www.instagram.com/barackobama/"

[[params.social]]
key = 1
name = "snapchat"
url = "https://www.snapchat.com/add/michelleobama"


