baseURL = 'http://www.rajwadkar.us/protean.github.io/'
languageCode = 'en-us'
title = 'ABC Widgets, Inc.'
theme = "nightfall"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
user = "print-USERNAME"
hostname = "print-HOSTNAME"
footerHtml = 'THIS IS THE FOOTER'
  [params.author]
    name = "MAIN SITE LABEL"  
    email = "email@address.com"  

readingTime = false  # Show reading time on post page
published = false  # Show published data on post page

[[params.social]]
key = 0
name = "instagram"
url = "https://www.instagram.com/barackobama/"
icon = "fa-brands fa-instagram"

[[params.social]]
key = 1
name = "snapchat"
url = "https://www.snapchat.com/add/michelleobama"
icon = "fa-brands fa-snapchat"


